kind: pipeline
name: Build Packages for Android
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: Perform Build
    image: gcr.io/mersive-kepler/android-builder
    commands:
      - ./build.sh
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      TARGET_API: 23
      ZLIB_VERSION: "1.2.11"
      MBEDTLS_VERSION: "2.23.0"
      CONAN_NON_INTERACTIVE: 1
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory-password
trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
---
kind: pipeline
name: Build Packages for Windows
type: docker

platform:
  os: windows
  arch: amd64

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

steps:
  - name: Perform Build
    image: grantsheehan/rust-windows # https://github.com/Mersive-Technologies/kepler-ci_cd/blob/master/drone/dockerfiles/rust-windows
    environment:
      CONAN_NON_INTERACTIVE: 1
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory-password
    commands:
      - powershell Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser
      - powershell .\build.ps1
